language: node_js

node_js:
  - "0.10"

env:
  - COVERAGE=true

before_script:
  - npm install -g bower
  - bower install

notifications:
  email: true

# whitelisted branches
branches:
  only:
    - master