language: node_js

node_js:
  - "0.10"

env:
  - COVERAGE=true

before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - bower install -f

notifications:
  email: true

# whitelisted branches
branches:
  only:
    - master